# Generated by Django 3.2.9 on 2022-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_address_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
