# Generated by Django 4.0.3 on 2022-03-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ManyToManyField(blank=True, to='Blog.blogs'),
        ),
    ]
