# Generated by Django 3.2.9 on 2022-05-11 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20220508_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='media',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
