# Generated by Django 3.2.9 on 2022-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_blogs_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
