# Generated by Django 3.2.9 on 2022-05-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_blogcategory_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
